// Generated by Wrangler by running `wrangler types`

interface Env {
	instant_coffee: KVNamespace;
	PUBLIC_URL: "https://instant-coffee.stevenpetryk.workers.dev";
	DISCORD_WEBHOOK_URL: string;
	DISCORD_WEBHOOK_HEARTBEAT_URL: string;
	OPENAI_API_KEY: string;
	JWT_SECRET: string;
}
