#:schema node_modules/wrangler/config-schema.json
name = "instant-coffee"
main = "src/index.ts"
compatibility_date = "2025-01-09"

# No public URL since this worker is meant for scheduled work
workers_dev = false

# Workers Logs
[observability]
enabled = true

[triggers]
# Run every 30 minutes
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "instant_coffee"
id = "48e99119a1e2475187e8bdbbb2af2704"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

[[migrations]]
tag = "v2"
deleted_classes = ["MyDurableObject"]
