#:schema node_modules/wrangler/config-schema.json
name = "instant-coffee"
main = "src/index.ts"
compatibility_date = "2025-03-03"
compatibility_flags = ["nodejs_compat"]

# Public URL so that we can serve image composites of the instant coffee labels
workers_dev = true

# Workers Logs
[observability]
enabled = true

[triggers]
# Run every hour
crons = ["0 * * * *"]

[images]
binding = "IMAGES"

[[kv_namespaces]]
binding = "instant_coffee"
id = "48e99119a1e2475187e8bdbbb2af2704"
# preview_id = "a0b0b589a45045f6af4549178c20f491"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

[[migrations]]
tag = "v2"
deleted_classes = ["MyDurableObject"]

[vars]
PUBLIC_URL = "https://instant-coffee.stevenpetryk.workers.dev"
